[project]
name = "my_ci_testing_project"
version = "0.1.0"

[build-system]
requires = ["setuptools"]

dependencies = [
    "pytest",
    "numpy",
    "pandas",
    "pytest-mpl",
    "pytest-regtest",
]